#!/bin/bash

set -e

CONTAINER_NAME="cevdetabbas.com"
BASE_DIR="/home/tm/Containers"
REPO_URL="https://github.com/cevdetabbas/cevdetabbas.com.git"
TARGET_DIR="$BASE_DIR/cevdetabbas.com"

echo "Stopping and removing container..."
docker stop $CONTAINER_NAME || true
docker rm $CONTAINER_NAME || true

echo "Deleting old folder..."
rm -rf "$TARGET_DIR"

echo "Cloning new repo..."
cd "$BASE_DIR"
git clone "$REPO_URL"

echo "Starting container..."
cd "$TARGET_DIR"
docker compose up -d

echo "Done!"
