#!/bin/bash

# Navigate to your repository directory
cd /home/tm/dockerProductionContainers/cevdetabbas.cevdetabbas.com

# Stage all changes (new, modified, deleted files)
git add .

# Commit changes with a message including the current date and time
git commit -m "Auto commit on $(date)"

# Push changes to GitHub
git push origin main

